jaffle_shop:

  target: dev
  outputs:
    dev:
      type: duckdb
      extensions:
        - aws
        - https
        - httpfs
        - ducklake
        - parquet
        - postgres
      secrets:
        - type: s3
          provider: credential_chain
          region: "us-east-1"