version: 2

models:
  - name: checkbook
    description: State of Iowa checkbook

    columns:
      - name: rec_no
      - name: fiscal_year
      - name: fiscal_year_period
      - name: accounting_period
      - name: service
      - name: department
      - name: fund_code
      - name: fund_name
      - name: appropriation_code
      - name: appropriation_name
      - name: program
      - name: expense_category
      - name: vendor
      - name: vendor_id
      - name: payment_id
      - name: payment_date
      - name: invoice_id
      - name: invoice_line
      - name: invoice_distribution_line
      - name: invoice_date
      - name: amount
      - name: description